styles = {
    "oil_on_canvas":"Oil on Canvas", 
    "digital_art":"Digital art", 
    "tilt_shift":"Tilt shift", 
    "macro":"Macro", 
    "illustration":"Illustration", 
    "abstract":"Abstract", 
    "portrait":"Portrait", 
    "clay":"Clay", 
    "cotton":"Cotton", 
    "wool":"Wool", 
    "wood_carving":"Wood Carving", 
    "fantasy":"Fantasy", 
    "concept_art":"Concept art", 
    "child’s_drawing":"Child’s drawing", 
    "crayon_drawing":"Crayon drawing", 
    "watercolor":"Watercolor", 
    "sharpie_drawing":"Sharpie drawing", 
    "pastel":"Pastel", 
    "pixel_art_(hit_or_miss,_results_may_vary)":"Pixel art (hit or miss, results may vary)", 
    "origami":"Origami", 
    "ukiyo-e":"Ukiyo-e", 
    "calligraphy":"Calligraphy", 
    "caricature":"Caricature", 
    "pixar":"Pixar", 
    "ghibli":"Ghibli", 
    "postage_stamp_art":"Postage stamp art", 
    "20-100mm_photography":"20-100mm photography", 
    "film":"Film", 
    "baroque":"Baroque", 
}

artists = {
    'greg_rutkowski_(digital_art)': 'Greg Rutkowski',
    'junji_ito_(manga)': 'Junji Ito',
    'annie_leibovitz_(portrait_photographer)': 'Annie Leibovitz (Portrait photographer)',
    'alphonse_mucha_(art_nouveau)': 'Alphonse Mucha (Art Nouveau)',
    'andrei_riabovitchev_(various)': 'Andrei Riabovitchev (Various)',
    'alfred_augustus_glendening_(19th_century_landscape_painter)':
    'Alfred Augustus Glendening (19th century landscape painter)',
    'alberto_vargas_(pinup_painter/artist)':
    'Alberto Vargas (Pinup painter/artist)',
    'artstation_(amalgamation_of_many_artists)':
    'Artstation (Amalgamation of many artists)',
    'pixiv_(amalgamation_of_many_artists)': 'Pixiv (Amalgamation of many artists)',
    'artgerm_(digital_artist)': 'Artgerm (Digital artist)',
    'van_gogh_(post-impressionism)': 'Van Gogh (Post-Impressionism)',
    'sir_john_tenniel_(illustration,_black_and_white)': 'Sir John Tenniel (Illustration, black and white)',
    'terry_richardson_(punk)': 'Terry Richardson (Punk)',
    'bouguereau_(neoclassicism)': 'Bouguereau (Neoclassicism)',
    'alex_grey_(psychedelic_paintings)': 'Alex Grey (Psychedelic paintings)',
    'monet_(impressionism)': 'Monet (Impressionism)',
    'ross_tran_(digital_art/anime/videogames)': 'Ross Tran (Digital Art/Anime/Videogames)',
    'craig_mullins_(digital_painting/brushstrokes)': 'Craig Mullins (Digital Painting/Brushstrokes)',
    'ilya_kuvshinov_(digital_illustrator/anime)': 'Ilya Kuvshinov (Digital Illustrator/Anime)',
    'magali_villeneuve_(digital_artist/fantasy)': 'Magali Villeneuve (Digital Artist/Fantasy)',
    'jeremy_lipking_(realist_painter/19th_century_style)': 'Jeremy Lipking (Realist Painter/19th Century Style)',
    'michael_garmash_(romantic_impressionist)': 'Michael Garmash (Romantic Impressionist)',
    'donato_giancola_(fantasy)': 'Donato Giancola (Fantasy)',
    'mandy_jurgens_(digital_art)': 'Mandy Jurgens (Digital Art)',
    'ruan_jia_(digital_paintings/chinese)': 'Ruan Jia (Digital Paintings/Chinese)',
    'marc_simonetti_(concept_art/illustrator)': 'Marc Simonetti (Concept Art/Illustrator)',
    'peter_mohrbacher_(surreal_fantasy)': 'Peter Mohrbacher (Surreal Fantasy)',
    'krenz_cushart_(digital_art/anime)': 'Krenz Cushart (Digital Art/Anime)',
    'james_jean_(abstract/baroque-inspired)': 'James Jean (Abstract/Baroque-inspired)'
}
